import Link from "next/link";
import { FIBER_REPS } from "@/lib/fiberReps";
import { SITE_NAME, getRepUrl } from "@/lib/site";

export const metadata = {
  title: `QR Kit | ${SITE_NAME}`,
  description: "Download real QR codes for every Fiber Crew rep page.",
};

export default function QrKitPage() {
  return (
    <main className="qrPage">
      <section className="qrHero">
        <div>
          <p className="hubEyebrow">QR kit</p>
          <h1>Every rep gets a scan point.</h1>
          <p>
            These are real SVG QR codes generated by the app. Use them for flyers,
            cards, stickers, shirts, or whatever chaotic object gets pointed at a customer.
          </p>
        </div>
        <Link href="/">Back to crew</Link>
      </section>

      <section className="qrGrid" aria-label="Rep QR codes">
        {FIBER_REPS.map((rep) => (
          <article className="qrCard" key={rep.slug} style={{ "--rep-accent": rep.accent || "#1aa260" } as React.CSSProperties}>
            <div className="qrCodeFrame">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={`/${rep.slug}/qr.svg`} alt={`QR code for ${rep.name}`} />
            </div>
            <div className="qrCardBody">
              <span>{rep.redirectUrl ? "External redirect" : "Rep page"}</span>
              <h2>{rep.name}</h2>
              <p>{getRepUrl(rep)}</p>
              <div className="qrActions">
                <a href={`/${rep.slug}/qr.svg`} download={`${rep.slug}-fiber-crew-qr.svg`}>Download SVG</a>
                <a href={rep.redirectUrl || `/${rep.slug}`}>Open page</a>
              </div>
            </div>
          </article>
        ))}
      </section>
    </main>
  );
}
